### ISSUE TITLE
Transformation transformers like BoxCoxTransformer need the numerical variable to have no NA value.

### ISSUE THREAD

**Issue by pradumna123** [solegalli/feature_engine#211]
**Describe the bug**

Transformation transformers like BoxCoxTransformer need the numerical variable to have no NA value.
the fit method throws an error "NA values encountered" if the training dataset has NA values.
Now if we impute the training dataset with a random number and skip imputing test data. The transform method from BoxCoxTransformer changes the test data and train data without any error.  I was wondering if we want similar behavior to fit and transform.

**Comment by solegalli** [comment]
Hi @pradumna123

I just checked the source code, and it has a check for na in both fit and transform methos, so it should raise an error in transform as well. In fact, the tests do check that an error is raised when na are present in the data when fit or transform. So I am not sure I understand the problem.

Could you copy and paste, attach or link the notebook / code that you are referring to? or tell me a bit more about what the problem is?

Thanks a lot!
