### ISSUE TITLE
add feature scaling transformers 

### ISSUE THREAD

**Issue by ashok49473** [solegalli/feature_engine#237]
Whenever I want to scale some numerical features I'm always importing transformers from sklearn. preprocessing.
We know that the sklearn transformers don't take our required variable names to scale (like feature engine) and they don't return a data frame. It becomes somewhat frustrating when using a Pipeline to preprocess the data as the next transformer may need a data frame to transform the variables.

It would be very useful to users in the data preprocessing Pipeline if we can add some feature scaling transformers like MinMaxScaler, StandardScaler, RobustScaler, etc...

-> As a simple alternative solution, we can create a custom transformer as given below

```
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator 
class CustomScaler(BaseEstimator):
  def __init__(self, variables):
    self.variables = variables
    self.scaler = StandardScaler()

  def fit(self, X, y=None):
     self.scaler.fit(X[self.variables])
     return self

  def transform(self, X):
     X[self.columns] = self.scaler.transform(X[self.columns])
     return X
```
**Additional context**
Feature scaling is also an important feature engineering step for linear models. 
We can easily handle scalable variables in a preprocessing pipeline.

**Comment by ashok49473** [comment]
@solegalli 
please let me know if this functionality already exists..

**Comment by solegalli** [comment]
Hi @ashok49473 

The idea is to use the scalers wrapped by the SklearnTransformerWrapper, so that 1) it returns a dataframe, and 2) we can select the variables to scale if we want to.

https://feature-engine.readthedocs.io/en/latest/wrappers/Wrapper.html

In fact, I can see you volunteered to create pipelines for the SklearnTransformerWrapper, so maybe you could include some examples with the scalers in the pipelines?

Cheers
Sole

**Comment by solegalli** [comment]
add an example with scalers in the rst file
