### ISSUE TITLE
one test fail using tox

### ISSUE THREAD

**Issue by indymnv** [solegalli/feature_engine#240]
I forked the project and follow the instructions on the README to collaborate, almost all tests passed but it fails with a specific test in test_outliers folder with test_winsorizer.py. Here is the error message:

```
   ________________________________ test_quantile_capping_both_tails_with_fold_15_percent ________________________________

df_normal_dist =          var
0   0.176405
1   0.040016
2   0.097874
3   0.224089
4   0.186756
..       ...
95  0.070657
96  0.001050
97  0.178587
98  0.012691
99  0.040199

[100 rows x 1 columns]

    def test_quantile_capping_both_tails_with_fold_15_percent(df_normal_dist):
        # test case 6: quantiles, right tail, fold 15%
        transformer = Winsorizer(capping_method="quantiles", tail="right", fold=0.15)
        X = transformer.fit_transform(df_normal_dist)

        # expected output
        df_transf = df_normal_dist.copy()
        df_transf["var"] = np.where(
            df_transf["var"] > 0.11823196128033647, 0.11823196128033647, df_transf["var"]
        )

        # test fit params
>       assert transformer.right_tail_caps_ == {"var": 0.11823196128033647}
E       AssertionError: assert {'var': 0.11823196128033646} == {'var': 0.11823196128033647}
E         Differing items:
E         {'var': 0.11823196128033646} != {'var': 0.11823196128033647}
E         Use -v to get the full diff

tests\test_outliers\test_winsorizer.py:141: AssertionError
```

I use Python 3.7 and windows 10

**Comment by solegalli** [comment]
Hi @indymnv 

Thanks for the interest. I am aware of this issue. It occurs because we use way to many decimals in the tests. We should round those values to 3.

We are fixing those as they come along. That means, every time a contributor has a problem with this test, we fix it in the same PR.

Alternatively, we could make a PR just to fix this across all tests. 

Were you interested in any particular issue to contribute?

**Comment by indymnv** [comment]
Well, I am a newbie in this, but I'd love to help with this project. if you want I will do a PR with all the tests. or if you have another issue just let me know.

**Comment by solegalli** [comment]
Awesome!! thanks!

This issue is actually an easy one, if you want to start with it.

You would basically need to go over all tests, and when we compare long numbers like the one in your error, you would have to replace the line of code by  something like this:

https://github.com/solegalli/feature_engine/blob/master/tests/test_outliers/test_winsorizer.py#L141

This file has a lot of those:
https://github.com/solegalli/feature_engine/blob/master/tests/test_outliers/test_winsorizer.py

If you want to make a PR with just that file modified, then we can work together through which other tests need updating

Thanks a lot

Sole

**Comment by indymnv** [comment]
Perfect, I will check this out.
