### ISSUE TITLE
modify _find_or_check_categorical_variables to support dtype='category'

### ISSUE THREAD

**Issue by bitsbuffer** [solegalli/feature_engine#259]
**Is your feature request related to a problem? Please describe.**
Currently, _find_or_check_categorical_variables in variable_manipulation.py only checks for type object to determine categorical variables.

**Describe the solution you'd like**
The method should be enhanced to support dtype="category" to support cases where user has used category datatype to optimise memory footprint of Pandas dataframe. 
(https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html)

**Comment by bitsbuffer** [comment]
@solegalli I can work on this and create a PR. Is that ok ?

**Comment by solegalli** [comment]
that would be wonderful :) @bitsbuffer

**Comment by datacubeR** [comment]
I will deeply appreciate this PR to be done since it is becoming very common to work with categories instead of objects in Pandas and OneHotEncoder is showing a very annoying error. I had a very hard time finding why OneHotEncoder (and probably other encoders) is raising the error because documentation refers to inputs as categorical variables when it should be referring to objects type. 

Even declaring what variables to be transformed in the variables parameter doesn't seem to work.
Let me know if I can help in some way to fix this issue, although a minor issue is being very annoying.

**Comment by bitsbuffer** [comment]
@solegalli Apologies for the delay. I can take this on priority.

**Comment by bitsbuffer** [comment]
Hi @solegalli I have created a PR, please review it and suggest the necessary changes.
https://github.com/solegalli/feature_engine/pull/260

**Comment by solegalli** [comment]
the main change for this issue has already been suggested [here](https://github.com/solegalli/feature_engine/pull/260/files#diff-9eb486aff6447df1b2837e699d0ccfceb256bfdf3e7b40cdbef45dc03abb4fb0).

The easiest would be to include these changes in a new PR and to finish off:

- expand the tests for that function [here](https://github.com/solegalli/feature_engine/blob/master/tests/test_variable_manipulation.py#L57)
- add 1-2 tests to each categorical encoder to make sure they return the expected value for each transformation

**Comment by bitsbuffer** [comment]
Hi @solegalli Apologise for the delay, I hope we can wait for this till this weekend.

**Comment by solegalli** [comment]
Hi @bitsbuffer this issue is almost ready in #264 

It wasn't as straightforward as I thought, because with the tests i realised that we needed more modifications to cast the variables after the encoding appropriately.

It would be great to have you on board though, would you like to check some of the other available issues in the repo?
