### ISSUE TITLE
Rare Label encoding attribute

### ISSUE THREAD

**Issue by carneche** [solegalli/feature_engine#297]
Hi, I wonder if there would be is an issue within the doc. In fact, I can't use the attribute "variables_" but it's possible to "variable" instead.

**Comment by solegalli** [comment]
`variables` is a parameter that you use when you set up the parameter for the first time. It can be `None`, a string with a column name, or a list of column names. With this parameters you indicate which variables you want to modify.

`variables_` is determined automatically by the transformer. If you set variables to a string or a list, then variables_ would take exactly the same values. If you set variables to None however, variables_ will be the list of all the categorical variables in your dataframe.

Does this answer the question? Otherwise, could you elaborate more on the issue?

**Comment by carneche** [comment]
For example, the code below works doesn't work:
`my_pipe.named_steps.rare_label_enc.variables_`

But when I use `my pipe.named_steps.rare labeling.variables` without" _ "at the end, it works. That's what I meant.

**Comment by solegalli** [comment]
I think it is probably a version problem. Which version of Feature-engine do you have installed?
 
If you dont know, from a notebook run the following:

```
import fearure_engine
feature_engine.__version__
```

The documentations correspond to versions 1.1 or bigger.

**Comment by carneche** [comment]
Indeed, it's was a 1.0.1 version problem. I've updated that and it's ok now.

**Comment by solegalli** [comment]
@carneche good to hear. I will close this issue then :)
