### ISSUE TITLE
Creation of new feature instead of overwriting the feature

### ISSUE THREAD

**Issue by GokulMahendran** [solegalli/feature_engine#47]
First thanks to the package. It simplifies the overall process. My issue is when using categorical
frequency encoder, why I am not unable to create a new feature instead of overwriting the categorical variable. It will be useful IF I use another categorical encoder function.
Correct me I am wrong if there is feature already in the package.

**Comment by solegalli** [comment]
Hi @GokulMahendran, this functionality is intentional, as machine learning models implemented by Scikit-learn or other packages, will only work with numerical variables. If you wish to retain the original categorical variable, then I suggest you capture the transformed data set in a different variable name. Eg: X_train_trasnformed = encoder.transform(X_train). Hope this helps.

**Comment by GokulMahendran** [comment]
Thanks for the reply mam. As you said, I have captured the output in the
separate variable and then merged with original data frame.
